@startuml ClassDiagram

' models

class Account {
  +id: String
  +userId: String
  +provider: String
  +refreshToken: String
  +accessToken: String
  +expires: DateTime
}

class Session {
  +id: String
  +userId: String
  +token: String
  +expires: DateTime
}

class User {
  +id: String
  +name: String
  +email: String
  +image: String
  +bio: String
  +accounts: Account[]
  +sessions: Session[]
  +listings: Listing[]
  +bids: Bid[]
  +watchedListings: Listing[]
}

class Listing {
  +id: String
  +title: String
  +description: String
  +price: Float
  +userId: String
  +expires: DateTime
  +createdAt: DateTime
  +images: ListingImages[]
  +bids: Bid[]
  +watchers: User[]
}

class ListingImages {
  +id: String
  +listingId: String
  +url: String
}

class Bid {
  +id: String
  +price: Float
  +userId: String
  +listingId: String
}

Account "1" -- "0..*" User
Session "1" -- "0..*" User
User "1" -- "0..*" Listing
User "1" -- "0..*" Bid
Listing "1" -- "0..*" ListingImages

' controllers

class ListingsController <<controller>>{
  +createListing()
  +updateListing()
  +deleteListing()
  +getListings()
  +getListingById()
  +getListingsByUserId()
}

class WatchlistController <<controller>>{
  +addToWatchlist()
  +removeFromWatchlist()
  +getWatchlist()
}

class AuthenticationController <<controller>>{
  +createSession()
  +updateSession()
  +deleteSession()
  +createUser()
  +deleteUser()
  +createAccount()
  +deleteAccount()
  +getUserGroup()
}

class BidController <<controller>>{
  +createBid()
  +updateBid()
  +deleteBid()
  +getBidsByListing()
  +getBidById()
  +getBidsByUserId()
}

class S3Controller <<controller>>{
  +uploadImage()
  +deleteImage()
}

' associations between routes and entities

AuthenticationController "1" -- "0..*" User : CRUD
AuthenticationController "1" -- "0..*" Account : CRUD
AuthenticationController "1" -- "0..*" Session : CRUD

ListingsController "1" -- "0..*" Listing : Creates/Reads/Updates
ListingsController "1" -- "1" AuthenticationController : Reads

WatchlistController "1" -- "0..*" Listing : Creates/Reads/Deletes
WatchlistController "1" -- "1" AuthenticationController : Reads

S3Controller "1" -- "0..*" ListingImages : Creates/Deletes
S3Controller "1" -- "1" AuthenticationController : Reads

BidController "1" -- "0..*" Bid : Creates
BidController "1" -- "1" AuthenticationController : Reads


interface UserInterface
interface ListingInterface
interface NewListingInterface
interface LoginInterface
interface WatchlistInterface
interface AboutInterface
interface LandingInterface
interface IconGenerator

' connect controllers to interfaces

UserInterface <|-- AuthenticationController
NewListingInterface <|-- ListingsController
LoginInterface <|-- AuthenticationController
WatchlistInterface <|-- WatchlistController
LandingInterface <|-- AuthenticationController
LandingInterface <|-- ListingsController
ListingInterface <|-- ListingsController
ListingInterface <|-- WatchlistController
ListingInterface <|-- BidController


@enduml
