name: Export PlantUML diagrams

on:
  push:
    branches:
      - '**'
    paths:
      - uml/**
  workflow_dispatch:

jobs:
  render-diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate SVG Diagrams
        uses: dreamsinbits/export-plantuml-action@v1
        with:
          args: -v -o out -tsvg uml
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_user_name: "PlantUML Diagramm Renderer"
          commit_user_email: "plantuml@martinmiglio.dev"
          commit_author: "PLantUML <plantuml@martinmiglio.dev>"
          commit_message: "Generated SVG images for PlantUML diagrams"
          branch: ${{ github.head_ref }}
